version: '3'
services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # Mount data directory if needed
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
